services:
  java-app:
    image: jonasdasneves/rei-dos-piratas
    env_file:
      - .env
    container_name: rei-dos-piratas
    restart: unless-stopped
    init: true
    ports:
      - "80:8080"


  postgres:
    image: postgres:18
    container_name: postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_DB: rei_dos_piratas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql


volumes:
  postgres_data:
