package br.com.fiap.rei_dos_piratas.domain.Enum;

public enum AsaasPaymentStatus {
    PENDING,
    RECEIVED,
    CONFIRMED,
    OVERDUE,
    REFUNDED,
    RECEIVED_IN_CASH,
    REFUND_REQUESTED,
    CHARGEBACK_REQUESTED,
    CHARGEBACK_DISPUTE,
    AWAITING_CHARGEBACK_REVERSAL,
    DUNNING_REQUESTED,
    DUNNING_RECEIVED,
    AWAITING_RISK_ANALYSIS
}
