spring.application.name=rei-dos-piratas
server.port=8080

#Database
spring.profiles.active=prod
spring.datasource.url=${DB_USER}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Segurança do Banco e Logs
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# A trava do Hikari
spring.datasource.hikari.maximum-pool-size=3

# Flyway
spring.flyway.encoding=UTF-8
spring.flyway.enabled=${FLYWAY_ENABLED:false}
spring.flyway.locations=classpath:db.migracao
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

jwt.secret= ${JWT_SECRET:596ae32c4416ca33e49258505dac9b7784292767303ce6f03926e86359009ca6ea5cd5d7}
jwt.expiration= ${JWT_EXPIRATION:86400000}

logging.level.org.springframework.security=TRACE
logging.level.br.com.fiap.projectmgtmvc=TRACE

# Feign Client Configuration
spring.cloud.openfeign.client.config.default.url=${ME_URL}
spring.cloud.openfeign.client.config.default.default-request-headers.accept=application/json
spring.cloud.openfeign.client.config.default.default-request-headers.user-agent=jonas.joliveira2024@gmail.com
spring.cloud.openfeign.client.config.default.connect-timeout=30000
spring.cloud.openfeign.client.config.default.read-timeout=30000
spring.cloud.openfeign.client.config.default.logger-level=basic

# Com contextId diferentes, definir URL por cliente evita fallback para load-balancer
spring.cloud.openfeign.client.config.frete-app.url=${ME_URL}
spring.cloud.openfeign.client.config.frete-token.url=${ME_URL}

spring.jackson.property-naming-strategy: SNAKE_CASE