INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('ARREPENDIMENTO', 'Arrependimento da compra', 1);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('NAO_ERA_O_ESPERADO', 'Produto nao era o que eu esperava', 1);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('PRODUTO_DANIFICADO', 'Produto chegou danificado', 1);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('PRODUTO_DEFEITUOSO', 'Produto com defeito', 1);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('PRODUTO_DIFERENTE_DO_ANUNCIO', 'Produto diferente do anunciado', 1);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('PRODUTO_ERRADO', 'Recebi um produto errado', 1);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('ATRASO_NA_ENTREGA', 'Atraso na entrega', 1);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('OUTRO', 'Outro motivo', 1);

