INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('ARREPENDIMENTO', 'Arrependimento da compra', TRUE);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('NAO_ERA_O_ESPERADO', 'Produto nao era o que eu esperava', TRUE);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('PRODUTO_DANIFICADO', 'Produto chegou danificado', TRUE);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('PRODUTO_DEFEITUOSO', 'Produto com defeito', TRUE);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('PRODUTO_DIFERENTE_DO_ANUNCIO', 'Produto diferente do anunciado', TRUE);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('PRODUTO_ERRADO', 'Recebi um produto errado', TRUE);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('ATRASO_NA_ENTREGA', 'Atraso na entrega', TRUE);
INSERT INTO MOTIVOS_DEVOLUCAO (codigo, descricao, ativo) VALUES ('OUTRO', 'Outro motivo', TRUE);

